// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7hbDgmjXCUWJNdh6emhxq19zQx_3EsKQ',
    appId: '1:743103917081:web:63a308bfb3cd7996a78e88',
    messagingSenderId: '743103917081',
    projectId: 'trackingsystem-kbp',
    authDomain: 'trackingsystem-kbp.firebaseapp.com',
    storageBucket: 'trackingsystem-kbp.firebasestorage.app',
    measurementId: 'G-61RCZVRL8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9WUQoUb3AM_YPWwShgvu2YI5coWwSx0Q',
    appId: '1:743103917081:android:c76cd3639d6e4296a78e88',
    messagingSenderId: '743103917081',
    projectId: 'trackingsystem-kbp',
    storageBucket: 'trackingsystem-kbp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4mwCKLi6AqidBrM1rDaQHcPDeiMTMDxE',
    appId: '1:743103917081:ios:a15c55854b4e4db1a78e88',
    messagingSenderId: '743103917081',
    projectId: 'trackingsystem-kbp',
    storageBucket: 'trackingsystem-kbp.firebasestorage.app',
    iosBundleId: 'com.example.livetrackingappMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4mwCKLi6AqidBrM1rDaQHcPDeiMTMDxE',
    appId: '1:743103917081:ios:a15c55854b4e4db1a78e88',
    messagingSenderId: '743103917081',
    projectId: 'trackingsystem-kbp',
    storageBucket: 'trackingsystem-kbp.firebasestorage.app',
    iosBundleId: 'com.example.livetrackingappMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7hbDgmjXCUWJNdh6emhxq19zQx_3EsKQ',
    appId: '1:743103917081:web:b5613fbde9caf7a6a78e88',
    messagingSenderId: '743103917081',
    projectId: 'trackingsystem-kbp',
    authDomain: 'trackingsystem-kbp.firebaseapp.com',
    storageBucket: 'trackingsystem-kbp.firebasestorage.app',
    measurementId: 'G-DDXT7J0R6E',
  );

}